apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: velero
spec:
  type: 0
  resourceID: 9c3ec2ae-8a4f-4ddf-a885-f5fbfc97f7d8
  clientID: 5eafadc5-172d-4397-9d91-b2a3a08d6acb



apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: velero-binding
spec:
  azureIdentity: velero
  selector: velero
