apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata: 
  name: mydisk.csi.azure.com 
provisioner: disk.csi.azure.com 
parameters: 
  skuname: StandardSSD_LRS 
reclaimPolicy: Retain 
volumeBindingMode: Immediate 
allowVolumeExpansion: true

---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: csi-app32
---
kind: Pod
apiVersion: v1
metadata:
  namespace: csi-app32
  name: csi-nginx
  annotations:
    backup.velero.io/backup-volumes: azuredisk01
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - image: nginx
      name: nginx
      command: [ "sleep", "1000000" ]
      volumeMounts:
        - name: azuredisk01
          mountPath: "/mnt/azuredisk"
  volumes:
    - name: azuredisk01
      persistentVolumeClaim:
        claimName: pvc-azuredisk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: csi-app32
  name: pvc-azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mydisk.csi.azure.com
---
