---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass 
metadata: 
  name: csi-azuredisk-vsc 
  annotations:
    velero.io/csi-volumesnapshot-class: "true"
driver: disk.csi.azure.com 
deletionPolicy: Delete
parameters:
  tags: 'class=westeurope,bar=bbb' 
  #location: northeurope
  #region: northeurope
  #resourceGroup: backups-aks1
  resourceGroup: backupwesteurope
  incremental: "false"


---
apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata: 
  name: mydisk.csi.azure.com 
provisioner: disk.csi.azure.com 
parameters: 
  #skuname: StandardSSD_LRS 
  skuname: StandardSSD_ZRS 
reclaimPolicy: Retain 
#volumeBindingMode: Immediate 
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: csi-app44
---
kind: Pod
apiVersion: v1
metadata:
  namespace: csi-app44
  name: csi-nginx
  annotations:
    backup.velero.io/backup-volumes: azuredisk44
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - image: nginx
      name: nginx
      command: [ "sleep", "1000000" ]
      volumeMounts:
        - name: azuredisk44
          mountPath: "/mnt/azuredisk"
  volumes:
    - name: azuredisk44
      persistentVolumeClaim:
        claimName: pvc-azuredisk44
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: csi-app44
  name: pvc-azuredisk44
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mydisk.csi.azure.com
---
