apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-diskfc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi


---

kind: Pod
apiVersion: v1
metadata:
  annotations:
    backup.velero.io/backup-volumes: myvolumediskfc
  name: mypoddiskfilecopy
spec:
  containers:
  - name: mypod
    image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: myvolumediskfc
  volumes:
    - name: myvolumediskfc
      persistentVolumeClaim:
        claimName: azure-managed-diskfc
